from concurrent.futures import ProcessPoolExecutor, as_completed
from os import cpu_count
from pathlib import Path
from time import time

from mctools.common.risk.scenario import Scenario
from mctools.common.risk.value import Value


def escape_latex(text: str) -> str:
    replacements = (
        ("\\", r"\textbackslash{}"),
        ("{", r"\{"),
        ("}", r"\}"),
        ("#", r"\#"),
        ("$", r"\$"),
        ("%", r"\%"),
        ("&", r"\&"),
        ("_", r"\_"),
        ("^", r"\textasciicircum{}"),
        ("~", r"\textasciitilde{}"),
    )
    escaped = text
    for old, new in replacements:
        escaped = escaped.replace(old, new)
    return escaped


def getPrintedValue(val=None, err=None, value: Value | None = None):
    """Return a string with the value to be printed

    If value is zero, no error is printed
    """
    if value is not None:
        val = value.val
        err = value.err

    epsilon = 1e-10
    color = ""
    bigerror = ""
    if val > 0.25:
        color = "[color=abovequater]"
    if val > 0.5:
        color = "[color=abovehalf]"

    if abs(val) > epsilon and err / val > 0.2:
        bigerror = "\\bigerror"
    return (
        "\\num{0.0}"
        if abs(val) < epsilon
        else "\\num%s{%f +- %f}%s" % (color, val, err, bigerror)
    )


def _evaluate_scenario(item: tuple[str, Scenario]) -> tuple[str, Scenario]:
    name, scenario = item
    scenario.evaluate()
    return name, scenario


class Case:
    def __init__(self, scenarios: dict[str, Scenario], name: str = ""):
        self.name = name
        self.scenarios = scenarios

    def evaluate(self, parallel: bool = False, max_workers: int | None = None):
        t_start = time()
        n_scenarios = len(self.scenarios)
        if parallel and n_scenarios > 1:
            if max_workers is None:
                max_workers = min(n_scenarios, cpu_count() or 1)
            else:
                max_workers = min(max_workers, n_scenarios)
            print(f"Evaluating {n_scenarios} scenarios with {max_workers} workers.")
            with ProcessPoolExecutor(max_workers=max_workers) as executor:
                futures = [
                    executor.submit(_evaluate_scenario, item)
                    for item in self.scenarios.items()
                ]
                for n_scenario, future in enumerate(as_completed(futures)):
                    scenario_name, scenario = future.result()
                    self.scenarios[scenario_name] = scenario
                    print(
                        f"Scenario {n_scenario+1:3d}/{n_scenarios:3d}: "
                        f"{(time()-t_start):4.2e} seconds ({scenario_name})"
                    )
            return

        for n_scenario, scenario in enumerate(self.scenarios):
            self.scenarios[scenario].evaluate()
            print(
                f"Scenario {n_scenario+1:3d}/{n_scenarios:3d}: "
                f"{(time()-t_start):4.2e} seconds ({scenario})"
            )

    def toLaTeX(
        self,
        command_output_file_name: Path,
        variable_output_file_name: Path,
        large_error_warnings=True,
    ):
        commands = self.createLaTeXCommands(large_error_warnings=large_error_warnings)
        with open(
            command_output_file_name, "w", encoding="utf-8"
        ) as command_output_file:
            command_output_file.write(commands)
        print(
            f"Created output file '{command_output_file_name}' which defines "
            r"the \rate commands."
        )
        variables = self.createAllVariableLaTeX(
            command_output_file_name=command_output_file_name
        )
        with open(
            variable_output_file_name, "w", encoding="utf-8"
        ) as variable_output_file:
            variable_output_file.write(variables)
        print(
            f"Created output file '{variable_output_file_name}' which calls "
            r"the \rate command for all possible arguments."
            "\n"
            r"It is assumed that the \rate commands are defined in a file "
            f"called '{command_output_file_name}'."
            "\nBuild document with\n\t"
            f"LATEX {variable_output_file_name} && "
            f"LATEX {variable_output_file_name}\n"
            "where LATEX is your LATEX compiler.\n"
            "(LATEX is invoked twice to build the table of contents.)"
        )

    def createLaTeXCommands(self, large_error_warnings: bool = True) -> str:
        buffer = [
            "% This file is generated by getmax.py. Don't edit it by hand.\n"
            "\\definecolor{abovequater}{HTML}{ff8b00} % for dose rates > 0.25 uSv/h\n"
            "\\definecolor{abovehalf}{HTML}{ff0000}   % for dose rates > 0.5 uSv/h\n"
        ]
        if large_error_warnings:
            buffer.append("\\newcommand\\bigerror{\\textcolor{red}{~(BIG ERROR!)}}\n")
        else:
            buffer.append("\\newcommand\\bigerror{}\n")
        buffer.append(
            "\\NewDocumentCommand\\rate{mmmmg}{%\n"
            "  % 1: scenario\n"
            "  % 2: region\n"
            "  % 3: area\n"
            "  % 4: zone\n"
        )

        for scenario in self.scenarios:
            escaped_scenario = escape_latex(scenario)
            buffer.append(
                r"\ifthenelse{\equal{#1}{"
                f"{escaped_scenario}"
                "}}{% "
                f"{escaped_scenario}\n"
            )
            for region in self.scenarios[scenario].data.sources:
                escaped_region = escape_latex(region)
                buffer.append(
                    r"  \ifthenelse{\equal{#2}{"
                    f"{escaped_region}"
                    "}}{% "
                    f"{escape_latex(self.scenarios[scenario][region].path)}\n"
                )
                for area in self.scenarios[scenario][region].sub_levels:
                    escaped_area = escape_latex(area)
                    buffer.append(
                        r"    \ifthenelse{\equal"
                        "{#3}{" + f"{escaped_area}"
                        "}}{% "
                        f"{escape_latex(self.scenarios[scenario][region][area].path)}\n"
                    )
                    for zone in self.scenarios[scenario][region][area].sub_levels:
                        escaped_zone = escape_latex(zone)
                        buffer.append(
                            r"      \ifthenelse{\equal{#4}{"
                            f"{escaped_zone}"
                            "}}{"
                            f"{getPrintedValue(value=self.scenarios[scenario][region][area][zone].value)}"
                            "}{"
                            f"% {escape_latex(self.scenarios[scenario][region][area][zone].path)}\n"
                        )
                    buffer.append(
                        "        "
                        + (
                            "}"
                            * len(
                                self.scenarios[scenario][region]
                                .sub_levels[area]
                                .sub_levels
                            )
                        )
                        + "%\n"
                    )
                    buffer.append("      }{}%\n")
                buffer.append("    }{}%\n")
            for combo in self.scenarios[scenario].data.arbitrary_level_combos:
                path = self.scenarios[scenario][combo].path
                combo_parts = path.split(".")[1:]
                n = len(combo_parts)
                escaped_parts = [escape_latex(p) for p in combo_parts]
                escaped_path = escape_latex(path)
                value_str = getPrintedValue(
                    value=self.scenarios[scenario][combo].value
                )
                for i, (escaped_part, arg_num) in enumerate(
                    zip(escaped_parts, range(2, n + 2))
                ):
                    indent = "  " * (i + 1)
                    is_last = i == n - 1
                    if is_last:
                        comment = f" {escaped_path}" if n == 1 else ""
                        buffer.append(
                            indent
                            + r"\ifthenelse{\equal{#"
                            + str(arg_num)
                            + "}{"
                            + escaped_part
                            + "}}{"
                            + value_str
                            + "}{}%"
                            + comment
                            + "\n"
                        )
                    elif i == 0:
                        buffer.append(
                            indent
                            + r"\ifthenelse{\equal{#"
                            + str(arg_num)
                            + "}{"
                            + escaped_part
                            + "}}{% "
                            + escaped_path
                            + "\n"
                        )
                    else:
                        buffer.append(
                            indent
                            + r"\ifthenelse{\equal{#"
                            + str(arg_num)
                            + "}{"
                            + escaped_part
                            + "}}{%\n"
                        )
                for i in range(n - 2, -1, -1):
                    buffer.append("  " * (i + 2) + "}{}%\n")
            buffer.append("}{}%\n")
        buffer.append("}%\n")
        return "".join(buffer)

    def createAllVariableLaTeX(
        self, command_output_file_name: Path, large_error_warnings: bool = True
    ) -> str:
        buffer = [
            r"\documentclass{article}"
            "\n\n"
            r"\usepackage[margin=1in]{geometry}"
            "\n"
            r"\usepackage{ifthen}"
            "\n"
            r"\usepackage{siunitx}"
            "\n"
            r"\sisetup{round-mode = uncertainty, round-precision = 1}"
            "\n"
            r"\usepackage{tikz}"
            "\n"
            "\n"
            r"\usepackage{xstring}"
            "\n"
            "\n"
            r"\usepackage{xparse}"
            "\n\n"
            r"\setlength\parindent{0pt}"
            "\n\n"
            r"\input{"
            f"{escape_latex(str(command_output_file_name))}"
            "}\n\n"
            r"\newcommand\print{%"
            "\n"
            r"  \scenario.\region.\area.\zone : \value"
            "\n}\n"
            r"\newcommand\printCombo{%"
            "\n"
            r"  \combo : \value"
            "\n}\n\n"
            r"\begin{document}"
            "\n"
            r"\tableofcontents"
            "\n"
        ]

        for scenario in self.scenarios:
            escaped_scenario = escape_latex(scenario)
            buffer.append(r"\section{" f"{escaped_scenario}" "}")
            buffer.append(r"\def\scenario{" f"{escaped_scenario}" "}\n")
            for region in self.scenarios[scenario].data.sources:
                escaped_region = escape_latex(region)
                buffer.append(r"\def\region{" f"{escaped_region}" "}\n")
                for area in self.scenarios[scenario][region].sub_levels:
                    escaped_area = escape_latex(area)
                    buffer.append(r"\def\area{" f"{escaped_area}" "}\n")
                    for zone in (
                        self.scenarios[scenario][region].sub_levels[area].sub_levels
                    ):
                        escaped_zone = escape_latex(zone)
                        buffer.append(r"\def\zone{" f"{escaped_zone}" "}\n")
                        buffer.append(
                            r"\def\value{\rate{"
                            f"{escaped_scenario}"
                            "}{"
                            f"{escaped_region}"
                            "}{"
                            f"{escaped_area}"
                            "}{"
                            f"{escaped_zone}"
                            "}}\n"
                            r"\print"
                            "\n\n"
                        )
            for combo in self.scenarios[scenario].data.arbitrary_level_combos:
                path = self.scenarios[scenario][combo].path
                combo_parts = path.split(".")[1:]
                while len(combo_parts) < 3:
                    combo_parts.append("")
                escaped_combo_parts = [escape_latex(p) for p in combo_parts]
                buffer.append(
                    r"\def\combo{"
                    f"{escape_latex(path)}"
                    "}\n"
                )
                buffer.append(
                    r"\def\value{\rate{"
                    f"{escaped_scenario}"
                    "}{"
                    f"{escaped_combo_parts[0]}"
                    "}{"
                    f"{escaped_combo_parts[1]}"
                    "}{"
                    f"{escaped_combo_parts[2]}"
                    "}}\n"
                    r"\printCombo"
                    "\n\n"
                )
        buffer.append(r"\end{document}")
        return "".join(buffer)

    def __getitem__(self, key: str):
        return self.scenarios[key]
