from pathlib import Path
from time import time

from mctools.common.risk.scenario import Scenario
from mctools.common.risk.value import Value


def getPrintedValue(val=None, err=None, value: Value | None = None):
    """Return a string with the value to be printed

    If value is zero, no error is printed
    """
    if value is not None:
        val = value.val
        err = value.err

    epsilon = 1e-10
    color = ""
    bigerror = ""
    if val > 0.25:
        color = "[color=abovequater]"
    if val > 0.5:
        color = "[color=abovehalf]"

    if abs(val) > epsilon and err / val > 0.2:
        bigerror = " \\bigerror"
    return (
        "\\num{0.0}"
        if abs(val) < epsilon
        else "\\num%s{%f +- %f}%s" % (color, val, err, bigerror)
    )


class Case:
    def __init__(self, scenarios: dict[str, Scenario], name: str = ""):
        self.name = name
        self.scenarios = scenarios

    def evaluate(self):
        t_start = time()
        n_scenarios = len(self.scenarios)
        for n_scenario, scenario in enumerate(self.scenarios):
            self.scenarios[scenario].evaluate()
            print(
                f"Scenario {n_scenario+1:3d}/{n_scenarios:3d}: "
                f"{(time()-t_start):4.2e} seconds ({scenario})"
            )

    def toLaTeX(
        self,
        command_output_file_name: Path,
        variable_output_file_name: Path,
        large_error_warnings=True,
    ):
        commands = self.createLaTeXCommands(large_error_warnings=large_error_warnings)
        with open(
            command_output_file_name, "w", encoding="utf-8"
        ) as command_output_file:
            command_output_file.write(commands)
        print(
            f"Created output file '{command_output_file_name}' which defines "
            r"the \rate commands."
        )
        variables = self.createAllVariableLaTeX(
            command_output_file_name=command_output_file_name
        )
        with open(
            variable_output_file_name, "w", encoding="utf-8"
        ) as variable_output_file:
            variable_output_file.write(variables)
        print(
            f"Created output file '{variable_output_file_name}' which calls "
            r"the \rate command for all possible arguments."
            "\n"
            r"It is assumed that the \rate commands are defined in a file "
            f"called '{command_output_file_name}'."
            "\nBuild document with\n\t"
            f"LATEX {variable_output_file_name} && "
            f"LATEX {variable_output_file_name}\n"
            "where LATEX is your LATEX compiler.\n"
            "(LATEX is invoked twice to build the table of contents.)"
        )

    def createLaTeXCommands(self, large_error_warnings: bool = True) -> str:
        buffer = [
            "% This file is generated by getmax.py. Don't edit it by hand.\n"
            "\\definecolor{abovequater}{HTML}{ff8b00} % for dose rates > 0.25 uSv/h\n"
            "\\definecolor{abovehalf}{HTML}{ff0000}   % for dose rates > 0.5 uSv/h\n"
        ]
        if large_error_warnings:
            buffer.append("\\newcommand\\bigerror{\\textcolor{red}{(BIG ERROR!)}}\n")
        else:
            buffer.append("\\newcommand\\bigerror{}\n")
        buffer.append(
            "\\NewDocumentCommand\\rate{mmmmg}{%\n"
            "  % 1: scenario\n"
            "  % 2: region\n"
            "  % 3: area\n"
            "  % 4: zone\n"
        )

        for scenario in self.scenarios:
            buffer.append(
                r"\ifthenelse{\equal{#1}{" f"{scenario}" "}}{% " f"{scenario}\n"
            )
            for region in self.scenarios[scenario].data.sources:
                buffer.append(
                    r"  \ifthenelse{\equal{#2}{"
                    f"{region}"
                    "}}{% "
                    f"{self.scenarios[scenario][region].path}\n"
                )
                for area in self.scenarios[scenario][region].sub_levels:
                    buffer.append(
                        r"    \ifthenelse{\equal"
                        "{#3}{" + f"{area}"
                        "}}{% "
                        f"{self.scenarios[scenario][region][area].path}\n"
                    )
                    for zone in self.scenarios[scenario][region][area].sub_levels:
                        buffer.append(
                            r"      \ifthenelse{\equal{#4}{"
                            f"{zone}"
                            "}}{"
                            f"{getPrintedValue(value=self.scenarios[scenario][region][area][zone].value)}"
                            "}{"
                            f"% {self.scenarios[scenario][region][area][zone].path}\n"
                        )
                    buffer.append(
                        "        "
                        + (
                            "}"
                            * len(
                                self.scenarios[scenario][region]
                                .sub_levels[area]
                                .sub_levels
                            )
                        )
                        + "\n"
                    )
                    buffer.append("      }{}%\n")
                buffer.append("    }{}%\n")
            buffer.append("  }{%\n")
            for combo in self.scenarios[scenario].data.arbitrary_level_combos:
                buffer.append(
                    r"\ifthenelse{\equal{#1}{"
                    f"{self.scenarios[scenario][combo].path}"
                    "}}{% "
                    f"{self.scenarios[scenario][combo].path}\n"
                    f"{getPrintedValue(value=self.scenarios[scenario][combo].value)}"
                )
                buffer.append("}{}\n")
            buffer.append("}%\n")
        buffer.append("}%\n")
        return "".join(buffer)

    def createAllVariableLaTeX(
        self, command_output_file_name: Path, large_error_warnings: bool = True
    ) -> str:
        buffer = [
            r"\documentclass{article}"
            "\n\n"
            r"\usepackage[margin=1in]{geometry}"
            "\n"
            r"\usepackage{ifthen}"
            "\n"
            r"\usepackage{siunitx}"
            "\n"
            r"\sisetup{round-mode = uncertainty, round-precision = 1}"
            "\n"
            r"\usepackage{tikz}"
            "\n"
            "\n"
            r"\usepackage{xstring}"
            "\n"
            "\n"
            r"\usepackage{xparse}"
            "\n\n"
            r"\setlength\parindent{0pt}"
            "\n\n"
            r"\input{"
            f"{command_output_file_name}"
            "}\n\n"
            r"\newcommand\print{%"
            "\n"
            r"  \scenario.\region.\area.\zone : \value"
            "\n}\n"
            r"\newcommand\printCombo{%"
            "\n"
            r"  \combo : \value"
            "\n}\n\n"
            r"\begin{document}"
            "\n"
            r"\tableofcontents"
            "\n"
        ]

        for scenario in self.scenarios:
            buffer.append(r"\section{" f"{scenario}" "}")
            buffer.append(r"\def\scenario{" f"{scenario}" "}\n")
            for region in self.scenarios[scenario].data.sources:
                buffer.append(r"\def\region{" f"{region}" "}\n")
                for area in self.scenarios[scenario][region].sub_levels:
                    buffer.append(r"\def\area{" f"{area}" "}\n")
                    for zone in (
                        self.scenarios[scenario][region].sub_levels[area].sub_levels
                    ):
                        buffer.append(r"\def\zone{" f"{zone}" "}\n")
                        buffer.append(
                            r"\def\value{\rate{"
                            f"{scenario}"
                            "}{"
                            f"{region}"
                            "}{"
                            f"{area}"
                            "}{"
                            f"{zone}"
                            "}}\n"
                            r"\print"
                            "\n\n"
                        )
            for combo in self.scenarios[scenario].data.arbitrary_level_combos:
                buffer.append(
                    r"\def\combo{" f"{self.scenarios[scenario][combo].path}" "}\n"
                )
                buffer.append(
                    r"\def\value{\rate{"
                    f"{self.scenarios[scenario][combo].path}"
                    "}{}{}{}}\n"
                    r"\printCombo"
                    "\n\n"
                )
        buffer.append(r"\end{document}")
        return "".join(buffer)

    def __getitem__(self, key: str):
        return self.scenarios[key]
