#!/usr/bin/env python
import sys
import struct
import argparse
from mctools.fluka.io.recordio import read_record
import ROOT
ROOT.PyConfig.IgnoreCommandLineOptions = True

ROOT.gROOT.ProcessLine(
"struct mydata {\
   Int_t mreg;\
   Int_t newreg;\
   Int_t jtrack;\
   Float_t etrack;\
   Double_t xsco;\
   Double_t ysco;\
   Double_t zsco;\
   Double_t cxtrck;\
   Double_t cytrck;\
   Double_t cztrck;\
   Double_t wtrack;\
};" );

def main():
    """ Example: USERDUMP to ROOT converter

    In this example, it is assumed that
    the USERDUMP card requests the BXDRAW call:
    USERDUMP       100.0                 3.0                              dump
    and the dump file is generated by these lines in the BXDRAW entry of mgdraw.f:
             write (IODRAW) MREG,NEWREG,JTRACK,ETRACK,
     &        XSCO,YSCO,ZSCO,CXTRCK,CYTRCK,CZTRCK,WTRACK
    """
    parser = argparse.ArgumentParser(description=main.__doc__,
                                     epilog="Homepage: https://github.com/kbat/mc-tools")
    parser.add_argument('userdump', type=str, help='USERDUMP binary output')
    parser.add_argument('root', type=str, help='ROOT output file name')

    args = parser.parse_args()

    mydata = ROOT.mydata()

    root = ROOT.TFile(args.root, "recreate")
    T = ROOT.TTree("T", args.userdump)
    T.Branch("data",mydata, "mreg/I:newreg/I:jtrack/I:etrack/F:xsco/D:ysco/D:zsco/D:cxtrck/D:cytrck/D:cztrck/D:wtrack/D")

    with open(args.userdump, "rb") as f:
        while True:

            # data = read_record(f)

            # Read leading record marker
            marker = f.read(4)
            if not marker:
                break  # EOF

            (record_len,) = struct.unpack("i", marker)

            # Read record data
            data = f.read(record_len)

            # Read trailing record marker
            (record_len2,) = struct.unpack("i", f.read(4))

            if record_len != record_len2:
                raise ValueError("Record length mismatch")

            mydata.mreg, mydata.newreg, mydata.jtrack, mydata.etrack, mydata.xsco, mydata.ysco, mydata.zsco, mydata.cxtrck, mydata.cytrck, mydata.cztrck, mydata.wtrack = struct.unpack("=3i8d", data)
            T.Fill()

        T.Write("", ROOT.TObject.kOverwrite)
#        root.Purge()
        root.Close()

if __name__ == "__main__":
    sys.exit(main())
