#!/bin/bash

VERBOSE=""

function help {

	echo "Usage: test [-v] file1 file2 ... "
	exit 0   

}

function performTest () {

	echo "Testing..."

	SUM=0
	ALL=0

	if [[ "$VERBOSE" == "-v" ]]; then
		shift 1
	fi

	for f in $@;
	do
		echo $f
		python nbmctaltest.py $VERBOSE $f
		OUT=$?
		#if [ $OUT -eq 5 ]; then
		#	echo $f >> macrobody_fails
		#	SUM=$(($SUM+1))
		#fi
		#if [ $OUT -eq 4 ]; then
		#	echo $f >> mesh_fails
		#	SUM=$(($SUM+1))
		#fi
		#if [ $OUT -eq 1 ]; then
		#	echo $f >> generic_fails
		#	SUM=$(($SUM+$OUT))
		#fi
		if [ $OUT -gt 0 ]; then
		#	echo $f >> mesh_fails_new
			SUM=$(($SUM+$OUT))
		fi
		#if [ $OUT -eq 0 ]; then
		#	echo $f >> successful_tests
		#fi
		ALL=$(($ALL+1))
	done

	echo "$SUM out of $ALL Failed"
	exit $SUM

}

if test $# -eq 0; then
    help
fi

while getopts "hv" option; do
    case $option in
        h) help;;
	v) VERBOSE="-v";;
    esac
done

performTest $@

